# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
more_books = [
  {:title => 'The Hobbit', :author => 'J.R.R. Tolkien', :summary => 'The Hobbit follows the quest of home-loving hobbit Bilbo Baggins to win a share of the treasure guarded by the dragon, Smaug. Bilbo''s journey takes him from light-hearted, rural surroundings into more sinister territory.The story is told in the form of an episodic quest, and most chapters introduce a specific creature, or type of creature, of Tolkien''s Wilderland. By accepting the disreputable, romantic, fey and adventurous side of his nature and applying his wits and common sense, Bilbo gains a new level of maturity, competence and wisdom. The story reaches its climax in the Battle of Five Armies, where many of the characters and creatures from earlier chapters re-emerge to engage in conflict.'},
  {:title => 'El Ingenioso hidalgo Don Quijote de la Mancha', :author => 'Miguel de Cervantes Saavedra', :summary => 'Primera obra genuinamente desmitificadora de la tradicion caballeresca y cortes, por el tratamiento burlesco que da a la misma. Representa la primera obra literaria que se puede clasificar como novela moderna y tambien la primera novela polifonica, y como tal, ejercio un influjo abrumador en toda la narrativa europea posterior.'},
  {:title => 'Twilight', :author => 'Stephenie Meyer', :summary => 'Twilight is a young-adult vampire-romance novel by author Stephenie Meyer. It is the first book of the Twilight series, and introduces seventeen-year-old Isabella "Bella" Swan, who moves from Phoenix, Arizona to Forks, Washington and finds her life in danger when she falls in love with a vampire, Edward Cullen. The novel is followed by New Moon, Eclipse, and Breaking Dawn.'},
 {:title => 'The Neverending Story', :author => 'Michael Ende', :summary => 'The majority of the story takes place in the parallel world of Fantastica (Phantasien in the original German version; referred to as Fantasia in the films), a world being destroyed by the Nothing, a mysterious force. The first protagonist is a young warrior who is asked by the Steward of The Empress of Fantastica to set off and find a way to stop the Nothing; the other protagonist is a boy from the real world, a reader of a novel with the same title, for whom the story gradually becomes more and more realistic.'},
{:title => 'The Pillars of the Earth', :author => 'Ken Follett', :summary => 'The Pillars of the Earth is a historical novel by Ken Follett published in 1989 about the building of a cathedral in the town of Kingsbridge, England. It is set in the middle of the 12th century, primarily during the Anarchy, between the time of the sinking of the White Ship and the murder of Thomas Becket. The book traces the development of Gothic architecture out of the preceding Romanesque architecture, and the fortunes of the Kingsbridge priory and village against the backdrop of historical events of the time.'},
{:title => 'Godel, Escher, Bach', :author => 'Douglas Hofstadter', :summary => 'By exploring common themes in the lives and works of logician Kurt Godel, artist M. C. Escher and composer Johann Sebastian Bach, GEB (as the book is also known) expounds concepts fundamental to mathematics, symmetry, and intelligence. Through illustration and analysis, the book discusses how self-reference and formal rules allow systems to acquire meaning despite being made of "meaningless" elements. It also discusses what it means to communicate, how knowledge can be represented and stored, the methods and limitations of symbolic representation, and even the fundamental notion of "meaning" itself.'},
{:title => 'The Unbearable Lightness of Being', :author => 'Milan Kundera', :summary => 'Challenging Friedrich Nietzsche''s concept of eternal recurrence (the idea that the universe and its events have already occurred and will recur ad infinitum), the story’s thematic meditations posit the alternative; that each person has only one life to live, and that which occurs in life occurs only once and never again — thus the "lightness" of being. In contrast, the concept of eternal recurrence imposes a "heaviness" on our lives and on the decisions we make (to borrow from Nietzsche''s metaphor, it gives them "weight".) Nietzsche believed this heaviness could be either a tremendous burden or great benefit depending on the individual''s perspective. The title also refers to the lightness of love and sex, which are themes of the novel. Kundera portrays love as fleeting, haphazard and perhaps based on endless strings of coincidences, despite holding such significance for humans.'}
]
# NOTE: the following line temporarily allows mass assignment
# (needed if you used attr_accessible/attr_protected in book.rb)
Book.send(:attr_accessible, :title, :author, :summary)
more_books.each do |book|
Book.create!(book)
end

